version: '3.3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    environment:
      - VIRTUAL_HOST=client.power.loc
    ports:
      - 80:80
